name: CFI Pros CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_lint_lightouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Use pnpm version 8

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Lint project
        run: pnpm lint # Runs 'next lint' as defined in package.json

      - name: Build project
        run: pnpm build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          # Need to output static site first for http-server
          # Update next.config.js or add export script if needed
          # For now, assuming default output directory is suitable
          serverCommand: npx http-server .next/server/app # Adjust path if needed
          serverReadyPattern: 'Available on:' # Wait for server start
          urls: 'http://localhost:8080' # URL served by http-server
          assertions: |
            {
              "assertMatrix": [
                {
                  "matchingUrlPattern": ".*",
                  "assertions": {
                    "categories:performance": ["warn", {"minScore": 0.8}],
                    "categories:accessibility": ["warn", {"minScore": 0.9}],
                    "categories:best-practices": ["error", {"minScore": 0.9}],
                    "categories:seo": ["warn", {"minScore": 0.9}]
                  }
                }
              ]
            }
          # uploadArtifacts: true # Optional: Upload reports as artifacts
          # temporaryPublicStorage: true # Optional: Upload reports to temporary storage
        env:
            LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }} # Required for status checks 